### ISSUE TITLE
Foreign key constraint incorrectly formed

### ISSUE THREAD

**Issue by mikerockett** [larapacks/authorization#13]
Using MariaDB 10.1.17 (not tested on MySQL), I receive the following exception when migrating the package's schema:

```
[Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1005 Can't create table `test`.`#sql-13dc_33`
  (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `permission_user`
  add constraint `permission_user_user_id_foreign` foreign key (`user_id`) references
  `users` (`id`) on delete cascade)
```

Using Laravel 5.3.22. Any ideas?

**Comment by mikerockett** [comment]
Ah, got it. It appears that the migration for this package is being called before my own migrations. As such, a foreign relation cannot be established on a table that does not yet exist (`users`).

**Comment by stevebauman** [comment]
Thanks for the quick update! Closing.

**Comment by mikerockett** [comment]
Well, I think this needs to be looked at. The date of the migration is what counts here, and it relies on users sticking to the default migration file for the users table. However, I delete that migration file in favour of a `make_auth_tables` migration which would have a newer date than the one shipped in this package.

Perhaps this file can be renamed to use the current date and time when running `vendor:publish`?

**Comment by stevebauman** [comment]
> Perhaps this file can be renamed to use the current date and time when running vendor:publish?

Well the issue with this is that for every time you run `vendor:publish`, it's going to create a new migration. Right now, the publish command won't continuously create new migration files with a new date since the file already exists.

I've actually never seen a laravel package that publishes it's migrations with the current date. Would you perhaps be able to provide an example?

Usually in this situation, I literally just rename the migration file time, run a `composer dump-autoload`. I think this allows the developer to be more aware that running `vendor:publish` will create another migration file since they were the ones to actually re-name the default published migration.

**Comment by mikerockett** [comment]
Ah, that is also true... It was just a quick half-baked solution-suggestion that sprung to mind.

It's a pity that Laravel doesn't look at foreign contraints before migrating to ensure that this kind of thing doesn't happen. Even better would be a migration instruction that tells Laravel that the migration relies on the existence of a particular table so it could re-sort the migrations based on that.

For now, manually renaming the auth migration I've created to a date before the package migration does the trick.

**Comment by stevebauman** [comment]
> It's a pity that Laravel doesn't look at foreign contraints before migrating to ensure that this kind of thing doesn't happen.

Yea I definitely agree. I think that there needs to be a solution somewhere since I've experienced this problem before as well.

I was thinking we could maybe check the existence of the migration files by verifying the actual class names of the migrations? Though I'm not sure if duplicate class names are allowed in composer `classmap`s, which would void this solution if they _were_ allowed?

**Comment by mikerockett** [comment]
> Though I'm not sure if duplicate class names are allowed in composer classmaps, which would void this solution if they were allowed?

I'm afraid I'm not knowledgeable enough from that point of view to advise. What I do know is that it would not be compatible with the way in which migration states are saved in the database.

Logically, however, I'm sure that a 'foreign constraint dependency-tree' could be formulated at migrate-time to ensure the correct order is processed. So in the case of this package, it would look like this:

```
users
    roles
    permissions
        role_user
        permission_user
        permission_role
```

Each indentation shows that the table on that line and any others with the same level of indentation depend on their parent (or, in effect, and as shown, the grandparent).

To me, this would solve the problem at hand, barring any oversights.
