### ISSUE TITLE
How to combine it with Laravel Passport?

### ISSUE THREAD

**Issue by garenk02** [larapacks/authorization#15]
Can I combine it with Laravel Passport on Laravel 5.4?
Really appreciate if u can give any example for that.

Thank's

**Comment by stevebauman** [comment]
Hi @garenk02, this works laravel's authorization by default. I haven't worked with Passport, but in the examples posted on Laravel.com, you should just be able to utilize the `can()` method instead of the `tokenCan()`:

```php
// Using tokenCan
Route::get('/orders', function (Request $request) {
    if ($request->user()->tokenCan('place-orders')) {
        //
    }
});
```

```php
// Using can
Route::get('/orders', function (Request $request) {
    if ($request->user()->can('place-orders')) {
        //
    }
});
```

Authorization just adds each users permission from the database to the guard at run-time:

https://github.com/larapacks/authorization/blob/master/src/AuthorizationServiceProvider.php#L36-L43

If you encounter issues, just give me a shout!
